# Identificación de riesgo de una persona tenga un ataque cardiaco utilizando Naive Bayes

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, KFold, RepeatedKFold, cross_val_score
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, classification_report

# Algortimo de Naive Bayes.
from sklearn.naive_bayes import MultinomialNB

In [2]:
datos=pd.read_csv("heart_attack.csv")

In [3]:
datos.head()

   age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  caa  output
0   63    1   3     145   233    1        0       150     0    0       1
1   37    1   2     130   250    0        1       187     0    0       1
2   41    0   1     130   204    0        0       172     0    0       1
3   56    1   1     120   236    0        1       178     0    0       1
4   57    0   0     120   354    0        1       163     1    0       1

In [4]:
datos[["age","trtbps","chol","thalachh"]].describe()

              age      trtbps        chol    thalachh
count  303.000000  303.000000  303.000000  303.000000
mean    54.366337  131.623762  246.264026  149.646865
std      9.082101   17.538143   51.830751   22.905161
min     29.000000   94.000000  126.000000   71.000000
25%     47.500000  120.000000  211.000000  133.500000
50%     55.000000  130.000000  240.000000  153.000000
75%     61.000000  140.000000  274.500000  166.000000
max     77.000000  200.000000  564.000000  202.000000

In [5]:
# NOTA: Para aplicar Naive Bayes cuando en el dataframe tenemos atributos 
# discretos y continuos, la idea es transformar los atributos continuos
# a discretos creando clases de categorías.

In [6]:
# Vamos a recodificar la edad
condiciones=[datos["age"]<40,(datos.age>=40)&(datos.age<60),datos["age"]>=60]
valores=[0,1,2]
datos["edad_c"]=np.select(condiciones,valores)

In [7]:
# Vamos a recodificar la presion arterial
condiciones=[datos["trtbps"]<=130,datos["trtbps"]>130]
valores=[0,1]
datos["trtbps_c"]=np.select(condiciones,valores)

In [8]:
# Vamos a recodificar los niveles de colesterol
condiciones=[datos["chol"]<=211,(datos["chol"]>211)&(datos["chol"]<274.5),datos["trtbps"]>=274.5]
valores=[0,1,2]
datos["chol_c"]=np.select(condiciones,valores)

In [9]:
# Vamos a recodificar los niveles de frecuencia máxima cardiaca
condiciones=[datos["thalachh"]<=133.5,(datos["thalachh"]>133.5)&(datos["thalachh"]<153),
             (datos["thalachh"]>=153)&(datos["thalachh"]>=166),datos["thalachh"]>166]
valores=[0,1,2,3]
datos["thalachh_c"]=np.select(condiciones,valores)

In [10]:
datos.head()

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,caa,output,edad_c,trtbps_c,chol_c,thalachh_c
0,63,1,3,145,233,1,0,150,0,0,1,2,1,1,1
1,37,1,2,130,250,0,1,187,0,0,1,0,0,1,2
2,41,0,1,130,204,0,0,172,0,0,1,1,0,0,2
3,56,1,1,120,236,0,1,178,0,0,1,1,0,1,2
4,57,0,0,120,354,0,1,163,1,0,1,1,0,0,0

In [11]:
# Seleccionamos el target
y=datos.output
# Seleccionamos los atributos
X=datos[["sex","cp","fbs","restecg","exng","caa","edad_c","trtbps_c","chol_c","thalachh_c"]]

In [12]:
X.head()

   sex  cp  fbs  restecg  exng  caa  edad_c  trtbps_c  chol_c  thalachh_c
0    1   3    1        0     0    0       2         1       1           1
1    1   2    0        1     0    0       0         0       1           2
2    0   1    0        0     0    0       1         0       0           2
3    1   1    0        1     0    0       1         0       1           2
4    0   0    0        1     1    0       1         0       0           0

In [13]:
# Definimos el modelo
modelo=MultinomialNB()
scores=cross_val_score(modelo,X,y,scoring="recall",cv=10,n_jobs=-1)
scores
print("La sensibilidad promedio es {:.3f} +/- {:.3f}".format(scores.mean(), scores.std()))

La sensibilidad promedio es 0.817 +/- 0.071

In [14]:
# Definimos el modelo
modelo=MultinomialNB()
scores=cross_val_score(modelo,X,y,scoring="accuracy",cv=10,n_jobs=-1)
scores
print("La sensibilidad promedio es {:.3f} +/- {:.3f}".format(scores.mean(), scores.std()))

La sensibilidad promedio es 0.789 +/- 0.028